/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InventoryProvenance } from './InventoryProvenance.js';
export * as factories from './factories/index.js';
export { InventoryProvenance__factory } from './factories/InventoryProvenance__factory.js';