/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InventoryProvenance {
      
    export type ProvenanceEventStruct = {eventHash: BytesLike, previousHash: BytesLike, eventType: BigNumberish, actor: AddressLike, timestamp: BigNumberish, productId: string, location: string, metadataURI: string}

    export type ProvenanceEventStructOutput = [eventHash: string, previousHash: string, eventType: bigint, actor: string, timestamp: bigint, productId: string, location: string, metadataURI: string] & {eventHash: string, previousHash: string, eventType: bigint, actor: string, timestamp: bigint, productId: string, location: string, metadataURI: string }
  
    }

  export interface InventoryProvenanceInterface extends Interface {
    getFunction(nameOrSignature: "allEvents" | "authorizeActor" | "authorizedActors" | "chainHead" | "getChainLength" | "getEvent" | "getProductChain" | "getProductEvents" | "owner" | "recordEvent" | "revokeActor" | "totalEvents" | "transferOwnership" | "verifyChain" | "verifyEvent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActorAuthorized" | "ActorRevoked" | "EventRecorded" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'allEvents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'authorizeActor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedActors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'chainHead', values: [string]): string;
encodeFunctionData(functionFragment: 'getChainLength', values: [string]): string;
encodeFunctionData(functionFragment: 'getEvent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductChain', values: [string]): string;
encodeFunctionData(functionFragment: 'getProductEvents', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordEvent', values: [string, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'revokeActor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalEvents', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyChain', values: [string]): string;
encodeFunctionData(functionFragment: 'verifyEvent', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'allEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeActor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedActors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainHead', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChainLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeActor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyEvent', data: BytesLike): Result;
  }

  
    export namespace ActorAuthorizedEvent {
      export type InputTuple = [actor: AddressLike];
      export type OutputTuple = [actor: string];
      export interface OutputObject {actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ActorRevokedEvent {
      export type InputTuple = [actor: AddressLike];
      export type OutputTuple = [actor: string];
      export interface OutputObject {actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EventRecordedEvent {
      export type InputTuple = [eventIndex: BigNumberish, productId: string, eventType: BigNumberish, eventHash: BytesLike, actor: AddressLike];
      export type OutputTuple = [eventIndex: bigint, productId: string, eventType: bigint, eventHash: string, actor: string];
      export interface OutputObject {eventIndex: bigint, productId: string, eventType: bigint, eventHash: string, actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InventoryProvenance extends BaseContract {
    
    connect(runner?: ContractRunner | null): InventoryProvenance;
    waitForDeployment(): Promise<this>;

    interface: InventoryProvenanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allEvents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, string, string, string] & {eventHash: string, previousHash: string, eventType: bigint, actor: string, timestamp: bigint, productId: string, location: string, metadataURI: string }],
      'view'
    >
    

    
    authorizeActor: TypedContractMethod<
      [actor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedActors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    chainHead: TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >
    

    
    getChainLength: TypedContractMethod<
      [productId: string, ],
      [bigint],
      'view'
    >
    

    
    getEvent: TypedContractMethod<
      [index: BigNumberish, ],
      [InventoryProvenance.ProvenanceEventStructOutput],
      'view'
    >
    

    
    getProductChain: TypedContractMethod<
      [productId: string, ],
      [bigint[]],
      'view'
    >
    

    
    getProductEvents: TypedContractMethod<
      [productId: string, offset: BigNumberish, limit: BigNumberish, ],
      [InventoryProvenance.ProvenanceEventStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordEvent: TypedContractMethod<
      [productId: string, eventType: BigNumberish, location: string, metadataURI: string, ],
      [[bigint, string] & {eventIndex: bigint, eventHash: string }],
      'nonpayable'
    >
    

    
    revokeActor: TypedContractMethod<
      [actor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalEvents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyChain: TypedContractMethod<
      [productId: string, ],
      [[boolean, bigint] & {valid: boolean, length: bigint }],
      'view'
    >
    

    
    verifyEvent: TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allEvents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, string, string, string] & {eventHash: string, previousHash: string, eventType: bigint, actor: string, timestamp: bigint, productId: string, location: string, metadataURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'authorizeActor'): TypedContractMethod<
      [actor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedActors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'chainHead'): TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getChainLength'): TypedContractMethod<
      [productId: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEvent'): TypedContractMethod<
      [index: BigNumberish, ],
      [InventoryProvenance.ProvenanceEventStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProductChain'): TypedContractMethod<
      [productId: string, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProductEvents'): TypedContractMethod<
      [productId: string, offset: BigNumberish, limit: BigNumberish, ],
      [InventoryProvenance.ProvenanceEventStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordEvent'): TypedContractMethod<
      [productId: string, eventType: BigNumberish, location: string, metadataURI: string, ],
      [[bigint, string] & {eventIndex: bigint, eventHash: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeActor'): TypedContractMethod<
      [actor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalEvents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyChain'): TypedContractMethod<
      [productId: string, ],
      [[boolean, bigint] & {valid: boolean, length: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verifyEvent'): TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'ActorAuthorized'): TypedContractEvent<ActorAuthorizedEvent.InputTuple, ActorAuthorizedEvent.OutputTuple, ActorAuthorizedEvent.OutputObject>;
getEvent(key: 'ActorRevoked'): TypedContractEvent<ActorRevokedEvent.InputTuple, ActorRevokedEvent.OutputTuple, ActorRevokedEvent.OutputObject>;
getEvent(key: 'EventRecorded'): TypedContractEvent<EventRecordedEvent.InputTuple, EventRecordedEvent.OutputTuple, EventRecordedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ActorAuthorized(address)': TypedContractEvent<ActorAuthorizedEvent.InputTuple, ActorAuthorizedEvent.OutputTuple, ActorAuthorizedEvent.OutputObject>;
      ActorAuthorized: TypedContractEvent<ActorAuthorizedEvent.InputTuple, ActorAuthorizedEvent.OutputTuple, ActorAuthorizedEvent.OutputObject>;
    

      'ActorRevoked(address)': TypedContractEvent<ActorRevokedEvent.InputTuple, ActorRevokedEvent.OutputTuple, ActorRevokedEvent.OutputObject>;
      ActorRevoked: TypedContractEvent<ActorRevokedEvent.InputTuple, ActorRevokedEvent.OutputTuple, ActorRevokedEvent.OutputObject>;
    

      'EventRecorded(uint256,string,uint8,bytes32,address)': TypedContractEvent<EventRecordedEvent.InputTuple, EventRecordedEvent.OutputTuple, EventRecordedEvent.OutputObject>;
      EventRecorded: TypedContractEvent<EventRecordedEvent.InputTuple, EventRecordedEvent.OutputTuple, EventRecordedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }